"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

from typing import TYPE_CHECKING

from magicgui import magic_factory
from magicgui.widgets import CheckBox, Container, create_widget
from qtpy.QtWidgets import QHBoxLayout, QPushButton, QWidget
from skimage.util import img_as_float

if TYPE_CHECKING:
    import napari


# Uses the `autogenerate: true` flag in the plugin manifest
# to indicate it should be wrapped as a magicgui to autogenerate
# a widget.
def threshold_autogenerate_widget(
    img: "napari.types.ImageData",
    threshold: "float",
) -> "napari.types.LabelsData":
    return img_as_float(img) > threshold


# the magic_factory decorator lets us customize aspects of our widget
# we specify a widget type for the threshold parameter
# and use auto_call=True so the function is called whenever
# the value of a parameter changes
@magic_factory(
    threshold={"widget_type": "FloatSlider", "max": 1}, auto_call=True
)
def threshold_magic_widget(
    img_layer: "napari.layers.Image", threshold: "float"
) -> "napari.types.LabelsData":
    return img_as_float(img_layer.data) > threshold


# if we want even more control over our widget, we can use
# magicgui `Container`
class ImageThreshold(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer
        # use create_widget to generate widgets from type annotations
        self._image_layer_combo = create_widget(
            label="Image", annotation="napari.layers.Image"
        )
        self._threshold_slider = create_widget(
            label="Threshold", annotation=float, widget_type="FloatSlider"
        )
        self._threshold_slider.min = 0
        self._threshold_slider.max = 1
        # use magicgui widgets directly
        self._invert_checkbox = CheckBox(text="Keep pixels below threshold")

        # connect your own callbacks
        self._threshold_slider.changed.connect(self._threshold_im)
        self._invert_checkbox.changed.connect(self._threshold_im)

        # append into/extend the container with your widgets
        self.extend(
            [
                self._image_layer_combo,
                self._threshold_slider,
                self._invert_checkbox,
            ]
        )

    def _threshold_im(self):
        image_layer = self._image_layer_combo.value
        if image_layer is None:
            return

        image = img_as_float(image_layer.data)
        name = image_layer.name + "_thresholded"
        threshold = self._threshold_slider.value
        if self._invert_checkbox.value:
            thresholded = image < threshold
        else:
            thresholded = image > threshold
        if name in self._viewer.layers:
            self._viewer.layers[name].data = thresholded
        else:
            self._viewer.add_labels(thresholded, name=name)


class ExampleQWidget(QWidget):
    # your QWidget.__init__ can optionally request the napari viewer instance
    # use a type annotation of 'napari.viewer.Viewer' for any parameter
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self.viewer = viewer

        btn = QPushButton("Click me!")
        btn.clicked.connect(self._on_click)

        self.setLayout(QHBoxLayout())
        self.layout().addWidget(btn)

    def _on_click(self):
        print("napari has", len(self.viewer.layers), "layers")


# #!/usr/bin/env python3
# # -*- coding: utf-8 -*-
# """
# RSM3D app — single-YAML persistence (simple, synchronous pipeline)

# Changes in this version:
# • "View RSM" is ABOVE "Export to VTK" at the left bottom of Column 3
# • Clicking the 📂 symbol on the DATA file opens a menu: "Pick File…" or "Pick Folder…"

# YAML: env RSM3D_DEFAULTS_YAML, else ~/.rsm3d_defaults.yaml
# """

# from __future__ import annotations

# import os
# import pathlib
# import re
# import numpy as np
# import importlib.resources
# import sys
# from typing import Any, Dict, List, Tuple

# import yaml
# import napari
# from qtpy import QtCore, QtWidgets, QtGui
# from napari.utils.notifications import show_error
# from magicgui.widgets import (
#     CheckBox, ComboBox, Container, FileEdit, FloatSpinBox,
#     Label, LineEdit, PushButton, SpinBox, TextEdit,
# )

# from rsm3d.data_io import RSMDataLoader, write_rsm_volume_to_vtr
# from rsm3d.data_viz import RSMNapariViewer, IntensityNapariViewer
# from rsm3d.rsm3d import RSMBuilder

# APP_ICON_PATH = (pathlib.Path(__file__).parent / "resview_icon.png").resolve()

# def load_app_icon() -> QtGui.QIcon | None:
#     if APP_ICON_PATH.is_file():
#         icon = QtGui.QIcon(str(APP_ICON_PATH))
#         return icon if not icon.isNull() else None
#     return None

# def apply_app_icon(app: QtWidgets.QApplication, win: QtWidgets.QWidget | None = None) -> None:
#     icon = load_app_icon()
#     if icon:
#         app.setWindowIcon(icon)
#         if win is not None:
#             try:
#                 win.setWindowIcon(icon)
#             except Exception:
#                 pass

# # ─────────────────────────────────────────────────────────────────────────────
# # Theme / QSS
# # ─────────────────────────────────────────────────────────────────────────────

# APP_QSS = """
# QMainWindow { background: #fafafa; }
# QGroupBox {
#     border: 1px solid #d9d9d9;
#     border-radius: 8px;
#     margin-top: 12px;
#     background: #ffffff;
#     font-weight: 600;
# }
# QGroupBox::title {
#     subcontrol-origin: margin;
#     subcontrol-position: top left;
#     padding: 6px 10px;
#     color: #2c3e50;
#     font-size: 18px;
#     font-weight: 700;
#     letter-spacing: 0.2px;
# }
# QSplitter::handle {
#     background: #e9edf3;
#     border-left: 1px solid #d0d4db;
#     border-right: 1px solid #ffffff;
# }
# QLabel { color: #34495e; }
# QLineEdit, QPlainTextEdit, QTextEdit, QComboBox, QDoubleSpinBox, QSpinBox {
#     border: 1px solid #d4d7dd;
#     border-radius: 6px;
#     padding: 4px 6px;
#     background: #ffffff;
# }
# QPushButton {
#     background: #eef2f7;
#     border: 1px solid #d4d7dd;
#     border-radius: 8px;
#     padding: 6px 10px;
#     font-weight: 600;
# }
# QPushButton:hover { background: #e6ebf3; }
# QPushButton:pressed { background: #dfe5ee; }
# """

# RUN_ALL_QSS = """
# QPushButton#RunAllPrimary {
#     background: #ff9800;
#     color: #ffffff;
#     border: 2px solid #e68900;
#     border-radius: 10px;
#     padding: 14px 20px;
#     font-size: 18px;
#     font-weight: 800;
# }
# QPushButton#RunAllPrimary:hover { background: #ffa726; }
# QPushButton#RunAllPrimary:pressed { background: #fb8c00; }
# """


# # ─────────────────────────────────────────────────────────────────────────────
# # YAML utils
# # ─────────────────────────────────────────────────────────────────────────────

# DEFAULTS_ENV = "RSM3D_DEFAULTS_YAML"
# os.environ.setdefault(
#     DEFAULTS_ENV,
#     str(pathlib.Path(__file__).with_name("rsm3d_defaults.yaml").resolve()),
# )

# def yaml_path() -> str:
#     p = os.environ.get(DEFAULTS_ENV, "").strip()
#     if p:
#         return os.path.abspath(os.path.expanduser(p))
#     return os.path.join(os.path.expanduser("~"), ".rsm3d_defaults.yaml")

# def ensure_yaml(path: str) -> None:
#     if os.path.isfile(path):
#         return
#     os.makedirs(os.path.dirname(path), exist_ok=True)
#     seed = {
#         "data": {"spec_file": None, "data_file": None, "scans": "", "only_hkl": None},
#         "ExperimentSetup": {
#             "distance": None, "pitch": None, "ycenter": None, "xcenter": None,
#             "xpixels": None, "ypixels": None, "energy": None, "wavelength": None,
#         },
#         "Crystal": {"ub": None},
#         "build": {"ub_includes_2pi": None, "center_is_one_based": None},
#         "crop": {"enable": None, "y_min": None, "y_max": None, "x_min": None, "x_max": None},
#         "regrid": {"space": None, "grid_shape": "", "fuzzy": None, "fuzzy_width": None, "normalize": None},
#         "view": {"log_view": None, "cmap": None, "rendering": None, "contrast_lo": None, "contrast_hi": None},
#         "export": {"vtr_path": None},
#     }
#     with open(path, "w", encoding="utf-8") as f:
#         yaml.safe_dump(seed, f, sort_keys=False)


# def format_ub_matrix(ub: Any) -> str:
#     if ub is None:
#         return ""
#     arr = np.asarray(ub, dtype=float)
#     if arr.ndim == 0:
#         return f"{arr.item():.6g}"
#     if arr.ndim == 1:
#         return " ".join(f"{v:.6g}" for v in arr)
#     if arr.ndim == 2:
#         return "\n".join(" ".join(f"{v:.6g}" for v in row) for row in arr)
#     return str(arr)

# def parse_ub_matrix(text: str) -> np.ndarray | None:
#     stripped = (text or "").strip()
#     if not stripped:
#         return None
#     rows: List[List[float]] = []
#     for line in stripped.splitlines():
#         parts = [p for p in re.split(r"[,\s]+", line.strip()) if p]
#         if parts:
#             rows.append([float(p) for p in parts])
#     if not rows:
#         return None
#     width = len(rows[0])
#     if any(len(row) != width for row in rows):
#         raise ValueError("UB rows must have equal length.")
#     return np.array(rows, dtype=float)


# def load_yaml(path: str) -> Dict[str, Any]:
#     try:
#         return yaml.safe_load(open(path, "r", encoding="utf-8")) or {}
#     except Exception:
#         return {}

# def save_yaml(path: str, doc: Dict[str, Any]) -> None:
#     try:
#         with open(path, "w", encoding="utf-8") as f:
#             yaml.safe_dump(doc, f, sort_keys=False)
#     except Exception as e:
#         show_error(f"Failed to write YAML: {e}")

# def as_path_str(v: Any) -> str:
#     if v is None:
#         return ""
#     try:
#         return os.fspath(v)
#     except TypeError:
#         return str(v)

# # ─────────────────────────────────────────────────────────────────────────────
# # Helpers
# # ─────────────────────────────────────────────────────────────────────────────

# def hsep(height: int = 10) -> Label:
#     w = Label(value="")
#     try:
#         w.native.setFrameShape(QtWidgets.QFrame.HLine)
#         w.native.setFrameShadow(QtWidgets.QFrame.Sunken)
#         w.native.setLineWidth(1)
#         w.native.setFixedHeight(height)
#     except Exception:
#         pass
#     return w

# def q_hsep(height: int = 10) -> QtWidgets.QWidget:
#     line = QtWidgets.QFrame()
#     line.setFrameShape(QtWidgets.QFrame.HLine)
#     line.setFrameShadow(QtWidgets.QFrame.Sunken)
#     line.setLineWidth(1)
#     line.setFixedHeight(height)
#     return line

# def parse_scan_list(text: str) -> List[int]:
#     if not text or not text.strip():
#         return []
#     out: set[int] = set()
#     for part in re.split(r"[,\s]+", text.strip()):
#         if not part:
#             continue
#         if "-" in part:
#             a, b = part.split("-", 1)
#             a, b = a.strip(), b.strip()
#             if a.isdigit() and b.isdigit():
#                 lo, hi = int(a), int(b)
#                 if lo > hi:
#                     lo, hi = hi, lo
#                 out.update(range(lo, hi + 1))
#             else:
#                 raise ValueError(f"Bad scan range: '{part}'")
#         else:
#             if part.isdigit():
#                 out.add(int(part))
#             else:
#                 raise ValueError(f"Bad scan id: '{part}'")
#     return sorted(out)

# def parse_axes_list(text: str) -> List[str]:
#     """Parse comma/space separated axis tokens like 'x+, y+, z-' -> ['x+','y+','z-']."""
#     if not text:
#         return []
#     return [p.strip() for p in re.split(r"[,\s]+", text) if p.strip()]

# def parse_grid_shape(text: str) -> Tuple[int | None, int | None, int | None]:
#     if text is None:
#         return (None, None, None)
#     s = text.strip()
#     if not s:
#         return (None, None, None)
#     parts = [p.strip() for p in s.split(",")]
#     if len(parts) == 1:
#         parts += ["*", "*"]
#     if len(parts) != 3:
#         raise ValueError("Grid must be 'x,y,z' (y/z may be '*').")
#     def one(p: str) -> int | None:
#         if p in ("*", "", None):
#             return None
#         if not p.isdigit():
#             raise ValueError(f"Grid size must be integer or '*', got '{p}'")
#         v = int(p)
#         if v <= 0:
#             raise ValueError("Grid sizes must be > 0")
#         return v
#     return tuple(one(p) for p in parts)  # type: ignore[return-value]

# def format_ub_matrix(ub: Any) -> str:
#     if ub is None:
#         return ""
#     try:
#         arr = np.asarray(ub, dtype=float)
#     except Exception:
#         return str(ub)
#     if arr.ndim == 0:
#         return f"{arr.item():.6g}"
#     if arr.ndim == 1:
#         return " ".join(f"{v:.6g}" for v in arr)
#     return "\n".join(" ".join(f"{v:.6g}" for v in row) for row in arr)

# def parse_ub_matrix(text: str) -> np.ndarray | None:
#     stripped = (text or "").strip()
#     if not stripped:
#         return None
#     rows: List[List[float]] = []
#     for line in stripped.splitlines():
#         parts = [p for p in re.split(r"[,\s]+", line.strip()) if p]
#         if parts:
#             rows.append([float(p) for p in parts])
#     if not rows:
#         return None
#     width = len(rows[0])
#     if any(len(row) != width for row in rows):
#         raise ValueError("UB rows must have equal length.")
#     return np.array(rows, dtype=float)


# def open_intensity_in_napari(path: str):
#     """Open a single data file or (fallback) load all tiffs from a directory."""
#     viewer = napari.Viewer()
#     p = path.strip()
#     if os.path.isfile(p):
#         try:
#             viewer.open(p)
#             return viewer
#         except Exception:
#             pass
#     # Fallback: scan directory for TIFFs
#     d = p if os.path.isdir(p) else os.path.dirname(p)
#     patterns = ["*.tif", "*.tiff", "*.TIF", "*.TIFF"]
#     opened = False
#     for pat in patterns:
#         try:
#             viewer.open(os.path.join(d, pat))
#             opened = True
#         except Exception:
#             pass
#     if not opened:
#         show_error("Could not open intensity. Provide a readable file or a folder with TIFF(s).")
#     return viewer

# def make_group(title: str, inner_widget: QtWidgets.QWidget) -> QtWidgets.QGroupBox:
#     box = QtWidgets.QGroupBox(title)
#     lay = QtWidgets.QVBoxLayout(box)
#     lay.setContentsMargins(12, 12, 12, 12)
#     lay.setSpacing(8)
#     lay.addWidget(inner_widget)
#     return box

# def make_scroll(inner: QtWidgets.QWidget) -> QtWidgets.QScrollArea:
#     wrapper = QtWidgets.QWidget()
#     v = QtWidgets.QVBoxLayout(wrapper)
#     v.setContentsMargins(8, 8, 8, 8)
#     v.setSpacing(8)
#     v.addWidget(inner)
#     sc = QtWidgets.QScrollArea()
#     sc.setWidgetResizable(True)
#     sc.setFrameShape(QtWidgets.QFrame.NoFrame)
#     sc.setWidget(wrapper)
#     return sc

# def set_file_button_symbol(fe: FileEdit, symbol: str = "📂") -> QtWidgets.QPushButton | None:
#     """Replace 'Select file' text with a simple symbol and return the button."""
#     try:
#         for btn in fe.native.findChildren(QtWidgets.QPushButton):
#             btn.setText(symbol)
#             btn.setMinimumWidth(32)
#             btn.setMaximumWidth(36)
#             btn.setCursor(QtCore.Qt.PointingHandCursor)
#             return btn
#     except Exception:
#         pass
#     return None

# def attach_dual_picker(fe: FileEdit, button: QtWidgets.QPushButton) -> None:
#     """
#     Attach a drop-down menu to the FileEdit button that lets the user pick
#     either a single file or a folder.
#     """
#     menu = QtWidgets.QMenu(button)
#     act_file = menu.addAction("Pick File…")
#     act_dir  = menu.addAction("Pick Folder…")

#     def pick_file():
#         start = as_path_str(fe.value).strip() or os.path.expanduser("~")
#         path, _ = QtWidgets.QFileDialog.getOpenFileName(button, "Select file", start)
#         if path:
#             fe.value = path

#     def pick_dir():
#         start = as_path_str(fe.value).strip() or os.path.expanduser("~")
#         path = QtWidgets.QFileDialog.getExistingDirectory(button, "Select folder", start)
#         if path:
#             fe.value = path

#     act_file.triggered.connect(pick_file)
#     act_dir.triggered.connect(pick_dir)

#     # Show the menu on button click (keep the nice single-symbol look)
#     def on_click():
#         menu.exec_(button.mapToGlobal(QtCore.QPoint(0, button.height())))
#     button.clicked.connect(on_click)

# # ─────────────────────────────────────────────────────────────────────────────
# # App (synchronous step-by-step pipeline)
# # ─────────────────────────────────────────────────────────────────────────────

# def main() -> None:
#     app = QtWidgets.QApplication.instance() or QtWidgets.QApplication(sys.argv)
#     apply_app_icon(app)
#     app.setStyleSheet(APP_QSS + RUN_ALL_QSS)

#     ypath = yaml_path()
#     ensure_yaml(ypath)

#     # ── Build UI ────────────────────────────────────────────────────────────
#     # Column 1: Data & Setup
#     spec_file_w = FileEdit(mode="r", label="SPEC file")
#     data_file_w = FileEdit(mode="r", label="DATA file")  # will support file OR folder via menu
#     scans_w     = LineEdit(label="Scans (e.g. 17, 18-22, 30)")
#     scans_w.tooltip = "Comma/range list. Examples: 17, 18-22, 30"
#     only_hkl_w  = CheckBox(label="Only HKL scans")

#     # turn file buttons into simple symbols + add dual picker on DATA file
#     _spec_btn = set_file_button_symbol(spec_file_w, "📂")
#     _data_btn = set_file_button_symbol(data_file_w, "📂")
#     if _data_btn is not None:
#         attach_dual_picker(data_file_w, _data_btn)

#     title_params = Label(value="<b>Experiment Setup</b>")
#     distance_w   = FloatSpinBox(label="Distance (m)", min=-1e9, max=1e9, step=1e-6)
#     pitch_w      = FloatSpinBox(label="Pitch (m)",    min=-1e9, max=1e9, step=1e-9)
#     ypixels_w    = SpinBox(label="Detector H (px)", min=0, max=10_000_000, step=1)
#     xpixels_w    = SpinBox(label="Detector W (px)", min=0, max=10_000_000, step=1)
#     ycenter_w    = SpinBox(label="BeamCenter H (px)", min=0,max=10_000_000, step=1)
#     xcenter_w    = SpinBox(label="BeamCenter W (px)", min=0,max=10_000_000, step=1)

#     energy_w     = FloatSpinBox(label="Energy (keV)", min=-1e9, max=1e9, step=1e-3)
#     wavelength_w = FloatSpinBox(label="Wavelength (Å)", min=1e-6, max=1e6, step=1e-3)
#     wavelength_w.tooltip = "Leave empty to derive from energy. < 1e-3 is meters → converted to Å."

#     title_crystal = Label(value="<b>Crystal</b>")
#     ub_matrix_w = TextEdit(label="UB (matrix)")
#     ub_matrix_w.tooltip = "Rows separated by newlines; values separated by spaces or commas."
#     ub_matrix_w.value = "1 0 0\n0 1 0\n0 0 1"  # 3x3 identity matrix as default
#     try:
#         ub_matrix_w.native.setMinimumHeight(80)
#     except Exception:
#         pass

#     # Column 1 bottom buttons
#     btn_load = PushButton(text="📂 Load Data")
#     btn_intensity = PushButton(text="📈 View Intensity")
#     btn_row1 = QtWidgets.QWidget()
#     row1 = QtWidgets.QHBoxLayout(btn_row1); row1.setContentsMargins(0,0,0,0); row1.setSpacing(8)
#     row1.addWidget(btn_load.native); row1.addWidget(btn_intensity.native); row1.addStretch(1)

#     col1 = Container(
#         layout="vertical",
#         widgets=[
#             spec_file_w, data_file_w, scans_w, only_hkl_w,
#             hsep(), title_params,
#             distance_w, pitch_w, ypixels_w, xpixels_w, ycenter_w, xcenter_w, energy_w, wavelength_w,
#             hsep(), title_crystal,
#             ub_matrix_w,
#         ],
#     )

#     # Column 2: Build & Regrid
#     title_build = Label(value="<b>RSM Builder</b>")
#     sample_axes_w = LineEdit(label="Sample axes")
#     sample_axes_w.value = "x+, y+, z-"
#     detector_axes_w = LineEdit(label="Detector axes")
#     detector_axes_w.value = "x+"
#     ub_2pi_w    = CheckBox(label="UB includes 2π")
#     center_one_based_w = CheckBox(label="1-based center")

#     title_regrid = Label(value="<b>Grid Settings</b>")
#     space_w      = ComboBox(label="Space", choices=["hkl", "q"])
#     grid_shape_w = LineEdit(label="Grid (x,y,z), '*' allowed")
#     grid_shape_w.tooltip = "Examples: 200,*,* or 256,256,256 or just 200"
#     fuzzy_w      = CheckBox(label="Fuzzy gridder")
#     fuzzy_width_w= FloatSpinBox(label="Width (fuzzy)", min=0.0, max=1e9, step=0.01)
#     normalize_w  = ComboBox(label="Normalize", choices=["mean", "sum"])

#     title_crop   = Label(value="<b>Crop Settings</b>")
#     crop_enable_w= CheckBox(label="Crop before regrid")
#     y_min_w      = SpinBox(label="y_min", min=0, max=10_000_000, step=1)
#     y_max_w      = SpinBox(label="y_max", min=0, max=10_000_000, step=1)
#     x_min_w      = SpinBox(label="x_min", min=0, max=10_000_000, step=1)
#     x_max_w      = SpinBox(label="x_max", min=0, max=10_000_000, step=1)

#     # Column 2 bottom buttons
#     btn_build   = PushButton(text="🔧 Build RSM Map")
#     btn_regrid  = PushButton(text="🧮 Regrid")
#     btn_row2 = QtWidgets.QWidget()
#     row2 = QtWidgets.QHBoxLayout(btn_row2); row2.setContentsMargins(0,0,0,0); row2.setSpacing(8)
#     row2.addWidget(btn_build.native); row2.addWidget(btn_regrid.native); row2.addStretch(1)

#     col2 = Container(
#         layout="vertical",
#         widgets=[
#             title_build, ub_2pi_w, center_one_based_w,
#             sample_axes_w, detector_axes_w,              # NEW (place before hsep or where desired)
#             hsep(),
#             title_regrid, space_w, grid_shape_w, fuzzy_w, fuzzy_width_w, normalize_w,
#             hsep(),
#             title_crop, crop_enable_w, y_min_w, y_max_w, x_min_w, x_max_w,
#             hsep(),
#         ],
#     )

#     # Column 3: View + Status/Progress + Export controls at bottom
#     title_view   = Label(value="<b>Napari Viewer</b>")
#     log_view_w   = CheckBox(label="Log view")
#     cmap_w       = ComboBox(label="Colormap", choices=["viridis", "inferno", "magma", "plasma", "cividis"])
#     rendering_w  = ComboBox(label="Rendering", choices=["attenuated_mip", "mip", "translucent"])
#     contrast_lo_w= FloatSpinBox(label="Contrast low (%)",  min=0.0, max=100.0, step=0.1)
#     contrast_hi_w= FloatSpinBox(label="Contrast high (%)", min=0.0, max=100.0, step=0.1)

#     status_label_w = Label(value="Status / Output")
#     status_w       = TextEdit(value="")
#     try:
#         status_w.native.setReadOnly(True)
#         status_w.native.setMinimumHeight(220)
#     except Exception:
#         pass

#     progress = QtWidgets.QProgressBar()
#     progress.setMinimum(0); progress.setMaximum(100); progress.setValue(0); progress.setTextVisible(True)

#     # Export path in column 3
#     export_vtr_w = FileEdit(mode="w", label="Output VTK (.vtr)")
#     set_file_button_symbol(export_vtr_w, "📂")

#     # Bottom action buttons for Column 3:
#     # LEFT: "View RSM" ABOVE "Export to VTK" (vertical)
#     # RIGHT: big "Run All"
#     btn_view    = PushButton(text="🔭 View RSM")
#     btn_export  = PushButton(text="💾 Export to VTK")
#     btn_run_all = PushButton(text="▶️ Run All")
#     btn_run_all.native.setObjectName("RunAllPrimary")
#     btn_run_all.native.setMinimumHeight(64)

#     left_bottom = QtWidgets.QWidget()
#     vleft = QtWidgets.QVBoxLayout(left_bottom); vleft.setContentsMargins(0,0,0,0); vleft.setSpacing(8)
#     vleft.addWidget(btn_view.native)
#     vleft.addWidget(btn_export.native)

#     btn_row3 = QtWidgets.QWidget()
#     row3 = QtWidgets.QHBoxLayout(btn_row3); row3.setContentsMargins(0,0,0,0); row3.setSpacing(12)
#     row3.addWidget(left_bottom)     # left column: View above Export
#     row3.addStretch(1)
#     row3.addWidget(btn_run_all.native)  # right big button

#     col3 = Container(
#         layout="vertical",
#         widgets=[
#             title_view, log_view_w, cmap_w, rendering_w, contrast_lo_w, contrast_hi_w,
#             hsep(),
#         ],
#     )

#     # Wrap columns in groups + scroll areas
#     g1 = make_group("Data", col1.native)
#     g1_lay = g1.layout()
#     g1_lay.addStretch(1)
#     g1_lay.addWidget(btn_row1)

#     g2 = make_group("Build", col2.native)
#     g2_lay = g2.layout()
#     g2_lay.addStretch(1)
#     g2_lay.addWidget(btn_row2)

#     g3 = make_group("View", col3.native)
#     g3_lay = g3.layout()
#     g3_lay.addWidget(q_hsep())
#     g3_lay.addWidget(QtWidgets.QLabel("<b>Status / Output</b>"))
#     g3_lay.addWidget(status_w.native)
#     g3_lay.addWidget(progress)
#     g3_lay.addWidget(q_hsep())
#     g3_lay.addWidget(QtWidgets.QLabel("<b>Export</b>"))
#     g3_lay.addWidget(export_vtr_w.native)
#     g3_lay.addStretch(1)
#     g3_lay.addWidget(q_hsep())
#     g3_lay.addWidget(btn_row3)  # bottom row: View above Export (left), Run All (right)

#     s1, s2, s3 = make_scroll(g1), make_scroll(g2), make_scroll(g3)

#     splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
#     splitter.addWidget(s1); splitter.addWidget(s2); splitter.addWidget(s3)
#     splitter.setHandleWidth(10); splitter.setChildrenCollapsible(False)
#     splitter.setStretchFactor(0, 1); splitter.setStretchFactor(1, 1); splitter.setStretchFactor(2, 1)
#     splitter.setSizes([440, 440, 440])

#     win = QtWidgets.QMainWindow()
#     win.setWindowTitle("ResView")
#     win.setCentralWidget(splitter)
#     win.resize(1320, 820)
#     status_bar = QtWidgets.QStatusBar(); win.setStatusBar(status_bar)
#     win.show()

#     # ── YAML binding (load → UI; UI → save)
#     ydoc = load_yaml(ypath)
#     widget_map: Dict[str, Dict[str, Any]] = {
#         "data": {"spec_file": spec_file_w, "data_file": data_file_w, "scans": scans_w, "only_hkl": only_hkl_w},
#         "ExperimentSetup": {
#             "distance": distance_w, "pitch": pitch_w, "ycenter": ycenter_w, "xcenter": xcenter_w,
#             "xpixels": xpixels_w, "ypixels": ypixels_w, "energy": energy_w, "wavelength": wavelength_w,
#         },
#         "Crystal": {
#             "ub": ub_matrix_w,
#         },
#         "build": {
#             "ub_includes_2pi": ub_2pi_w,
#             "center_is_one_based": center_one_based_w,
#             "sample_axes": sample_axes_w,
#             "detector_axes": detector_axes_w,
#         },
#         "crop": {"enable": crop_enable_w, "y_min": y_min_w, "y_max": y_max_w, "x_min": x_min_w, "x_max": x_max_w},
#         "regrid": {"space": space_w, "grid_shape": grid_shape_w, "fuzzy": fuzzy_w, "fuzzy_width": fuzzy_width_w, "normalize": normalize_w},
#         "view": {"log_view": log_view_w, "cmap": cmap_w, "rendering": rendering_w, "contrast_lo": contrast_lo_w, "contrast_hi": contrast_hi_w},
#         "export": {"vtr_path": export_vtr_w},
#     }

#     def set_widget(widget: Any, value: Any) -> None:
#         try:
#             if value is None:
#                 return
#             if isinstance(widget, (FloatSpinBox, SpinBox)):
#                 widget.value = float(value) if isinstance(widget, FloatSpinBox) else int(value)
#             elif isinstance(widget, CheckBox):
#                 widget.value = bool(value)
#             elif isinstance(widget, ComboBox):
#                 sval = str(value)
#                 if sval in widget.choices:
#                     widget.value = sval
#             elif isinstance(widget, (LineEdit, TextEdit, FileEdit)):
#                 widget.value = str(value)
#         except Exception:
#             pass

#     for section, mapping in widget_map.items():
#         vals = ydoc.get(section, {})
#         for key, widget in mapping.items():
#             set_widget(widget, vals.get(key, None))
#     for s in widget_map:
#         ydoc.setdefault(s, {})
#     if not str(ydoc["Crystal"].get("ub") or "").strip():
#         ydoc["Crystal"]["ub"] = ub_matrix_w.value
#     save_yaml(ypath, ydoc)

#     def val_for_yaml(widget: Any, section: str, key: str) -> Any:
#         if section == "ExperimentSetup" and key == "wavelength":
#             txt = str(widget.value).strip()
#             if txt.lower() in {"", "none", "null"}:
#                 return None
#             try:
#                 return float(txt)
#             except Exception:
#                 return txt
#         if section == "Crystal" and key == "ub":
#             txt = str(widget.value).strip()
#             return txt or None
#         if isinstance(widget, FloatSpinBox):
#             return float(widget.value)
#         if isinstance(widget, SpinBox):
#             return int(widget.value)
#         if isinstance(widget, CheckBox):
#             return bool(widget.value)
#         if isinstance(widget, ComboBox):
#             return str(widget.value)
#         if isinstance(widget, (LineEdit, TextEdit, FileEdit)):
#             return str(widget.value)
#         return widget.value

#     def on_changed(section: str, key: str, widget: Any) -> None:
#         ydoc.setdefault(section, {})
#         ydoc[section][key] = val_for_yaml(widget, section, key)
#         save_yaml(ypath, ydoc)

#     for section, mapping in widget_map.items():
#         for key, widget in mapping.items():
#             widget.changed.connect(lambda *_, s=section, k=key, w=widget: on_changed(s, k, w))

#     # ── Status / progress helpers (synchronous) ─────────────────────────────
#     def pump(ms: int = 0):
#         QtWidgets.QApplication.processEvents(QtCore.QEventLoop.AllEvents, ms)

#     def status(msg: str) -> None:
#         try:
#             status_w.native.append(msg)
#         except Exception:
#             status_w.value = (status_w.value or "") + (("\n" if status_w.value else "") + msg)
#         status_bar.showMessage(msg, 3000)

#     def set_progress(value: int | None, *, busy: bool = False):
#         if busy:
#             progress.setRange(0, 0)
#         else:
#             progress.setRange(0, 100)
#             progress.setValue(int(value or 0))

#     def set_busy(b: bool):
#         for btn in (btn_load, btn_intensity, btn_build, btn_regrid, btn_view, btn_run_all, btn_export):
#             try:
#                 btn.native.setEnabled(not b)
#             except Exception:
#                 pass

#     # ── App state
#     # (find the first active state dict for the running version; add grid_space)
#     state: Dict[str, Any] = dict(loader=None, builder=None, grid=None, edges=None, grid_space=None)

#     # ── Actions ─────────────────────────────────────────────────────────────
#     def on_view_intensity():
#         loader = state.get("loader")
#         if loader is None:
#             show_error("Load data first.")
#             return

#         # Optionally coerce to a plain Python list of 2D arrays:
#         _, _, df = loader.load()
#         frames = list(df.intensity)   # each item is a 2D array

#         viewer = IntensityNapariViewer(
#             frames,                               # list of 2D frames
#             name="Intensity",
#             log_view=True,
#             contrast_percentiles=(1.0, 99.8),
#             cmap="inferno",
#             rendering="attenuated_mip",
#             add_timeseries=True,
#             add_volume=True,
#             scale_tzyx=(1.0, 1.0, 1.0),
#             pad_value=np.nan,                     # or 0.0 if you prefer black padding
#         ).launch()

#         state["intensity_viewer"] = viewer

#     def apply_ub_from_widget() -> bool:
#         loader = state.get("loader")
#         if loader is None:
#             return True
#         try:
#             parsed = parse_ub_matrix(ub_matrix_w.value)
#         except ValueError as exc:
#             show_error(f"Invalid UB: {exc}")
#             return False
#         state["builder"] = None
#         state["ub"] = parsed
#         try:
#             if hasattr(loader, "set_ub"):
#                 loader.set_ub(parsed)
#             else:
#                 setattr(loader, "ub", parsed)
#         except Exception as exc:
#             show_error(f"Failed to set UB: {exc}")
#             return False
#         return True

#     def on_load() -> None:
#         spec = as_path_str(spec_file_w.value).strip()
#         dpath = as_path_str(data_file_w.value).strip()
#         try:
#             scans = parse_scan_list((scans_w.value or "").strip())
#         except Exception as e:
#             show_error(str(e)); return

#         if not spec or not os.path.isfile(spec):
#             show_error("Select a valid SPEC file."); return
#         if not (os.path.isfile(dpath) or os.path.isdir(dpath)):
#             show_error("Select a valid DATA file (or a folder)."); return
#         if not scans:
#             show_error("Enter at least one scan (e.g. '17, 18-22')."); return

#         set_busy(True); set_progress(None, busy=True); status(f"Loading scans {scans}…"); pump(50)
#         try:
#             tiff_arg = dpath if os.path.isdir(dpath) else (os.path.dirname(dpath) or ".")
#             loader = RSMDataLoader(
#                 spec,
#                 yaml_path(),
#                 tiff_arg,
#                 selected_scans=scans,
#                 process_hklscan_only=bool(only_hkl_w.value),
#             )
#             load_result = loader.load()
#             ub_from_load = None
#             if isinstance(load_result, tuple) and len(load_result) >= 2:
#                 ub_from_load = load_result[1]
#             if ub_from_load is None:
#                 ub_from_load = getattr(loader, "ub", None)
#             state["ub"] = ub_from_load
#             ub_matrix_w.value = format_ub_matrix(ub_from_load)
#             state["loader"] = loader
#             state["builder"] = None
#             state["grid"] = state["edges"] = None
#             set_progress(25, busy=False); status("Data loaded.")
#         except Exception as e:
#             show_error(f"Load error: {e}")
#             set_progress(0, busy=False); status(f"Load failed: {e}")
#         finally:
#             set_busy(False)

#     def on_build() -> None:
#         if state.get("loader") is None:
#             show_error("Load data first."); return

#         set_busy(True); set_progress(None, busy=True); status("Computing Q/HKL/intensity…"); pump(50)
#         try:
#             b = RSMBuilder(
#                 state["loader"],
#                 sample_axes=parse_axes_list(sample_axes_w.value),
#                 detector_axes=parse_axes_list(detector_axes_w.value),
#                 ub_includes_2pi=bool(ub_2pi_w.value),
#                 center_is_one_based=bool(center_one_based_w.value),
#             )
#             b.compute_full(verbose=False)
#             state["builder"] = b
#             state["grid"] = state["edges"] = None
#             set_progress(50, busy=False); status("RSM map built.")
#         except Exception as e:
#             show_error(f"Build error: {e}")
#             set_progress(40, busy=False); status(f"Build failed: {e}")
#         finally:
#             set_busy(False)

#     def on_regrid() -> None:
#         b = state.get("builder")
#         if b is None:
#             show_error("Build the RSM map first."); return

#         try:
#             gx, gy, gz = parse_grid_shape(grid_shape_w.value)
#         except Exception as e:
#             show_error(str(e)); return
#         if gx is None:
#             show_error("Grid X (first value) is required (e.g., 200,*,*)."); return

#         do_crop = bool(crop_enable_w.value)
#         ymin, ymax = int(y_min_w.value), int(y_max_w.value)
#         xmin, xmax = int(x_min_w.value), int(x_max_w.value)

#         set_busy(True); set_progress(None, busy=True)
#         status(f"Regridding to {space_w.value.upper()} grid {(gx, gy, gz)}…"); pump(50)

#         try:
#             if do_crop:
#                 if ymin >= ymax or xmin >= xmax:
#                     raise ValueError("Crop bounds must satisfy y_min < y_max and x_min < x_max.")
#                 if state.get("loader") is None:
#                     raise RuntimeError("Internal error: loader missing; run Build again.")
#                 b = RSMBuilder(
#                     state["loader"],
#                     sample_axes=parse_axes_list(sample_axes_w.value),
#                     detector_axes=parse_axes_list(detector_axes_w.value),
#                     ub_includes_2pi=bool(ub_2pi_w.value),
#                     center_is_one_based=bool(center_one_based_w.value),
#                 )
#                 b.compute_full(verbose=False)
#                 b.crop_by_positions(y_bound=(ymin, ymax), x_bound=(xmin, xmax))

#             kwargs = dict(
#                 space=space_w.value,
#                 grid_shape=(gx, gy, gz),
#                 fuzzy=bool(fuzzy_w.value),
#                 normalize=normalize_w.value,
#                 stream=True,
#             )
#             if bool(fuzzy_w.value) and (fuzzy_width_w.value or 0) > 0:
#                 kwargs["width"] = float(fuzzy_width_w.value)

#             grid, edges = b.regrid_xu(**kwargs)
#             state["grid"], state["edges"] = grid, edges
#             set_progress(75, busy=False); status("Regrid completed.")
#         except Exception as e:
#             show_error(f"Regrid error: {e}")
#             set_progress(60, busy=False); status(f"Regrid failed: {e}")
#         finally:
#             set_busy(False)

#     def on_view() -> None:
#         if state.get("grid") is None or state.get("edges") is None:
#             show_error("Regrid first."); return
#         try:
#             lo = float(contrast_lo_w.value); hi = float(contrast_hi_w.value)
#             if not (0 <= lo < hi <= 100):
#                 raise ValueError("Contrast % must satisfy 0 ≤ low < high ≤ 100")

#             set_progress(None, busy=True); status("Opening RSM viewer…"); pump(50)
#             viz = RSMNapariViewer(
#                 state["grid"],
#                 state["edges"],
#                 space=space_w.value,
#                 name="RSM3D",
#                 log_view=bool(log_view_w.value),
#                 contrast_percentiles=(lo, hi),
#                 cmap=cmap_w.value,
#                 rendering=rendering_w.value,
#             )
#             viz.launch()
#             set_progress(100, busy=False); status("RSM viewer opened.")
#         except Exception as e:
#             show_error(f"View error: {e}")
#             set_progress(80, busy=False); status(f"View failed: {e}")

#     def on_export_vtk() -> None:
#         if state.get("grid") is None or state.get("edges") is None:
#             show_error("Regrid first, then export."); return
#         out_path = as_path_str(export_vtr_w.value).strip()
#         if not out_path:
#             show_error("Choose an output .vtr file path."); return
#         if not out_path.lower().endswith(".vtr"):
#             out_path += ".vtr"
#         try:
#             set_busy(True); set_progress(None, busy=True)
#             status(f"Exporting VTK (.vtr) → {out_path}"); pump(50)
#             write_rsm_volume_to_vtr(state["grid"], state["edges"], out_path, binary=False, compress=True)
#             set_progress(100, busy=False); status(f"Exported: {out_path}")
#         except Exception as e:
#             show_error(f"Export error: {e}")
#             set_progress(0, busy=False); status(f"Export failed: {e}")
#         finally:
#             set_busy(False)

#     def on_run_all() -> None:
#         btn_run_all.native.setEnabled(False)
#         try:
#             set_progress(0, busy=False); status("Running pipeline (Load → Build → Regrid → View)…")
#             on_load()
#             if state.get("loader") is None: return
#             on_build()
#             if state.get("builder") is None: return
#             on_regrid()
#             if state.get("grid") is None or state.get("edges") is None: return
#             on_view()
#             status("Run All completed.")
#         finally:
#             btn_run_all.native.setEnabled(True)

#     # Connect buttons
#     btn_intensity.clicked.connect(on_view_intensity)
#     btn_load.clicked.connect(on_load)
#     btn_build.clicked.connect(on_build)
#     btn_regrid.clicked.connect(on_regrid)
#     btn_view.clicked.connect(on_view)
#     btn_export.clicked.connect(on_export_vtk)
#     btn_run_all.clicked.connect(on_run_all)

#     # Keep saving YAML on changes
#     def on_changed(section: str, key: str, widget: Any) -> None:
#         ydoc.setdefault(section, {})
#         ydoc[section][key] = (
#             None if (section == "ExperimentSetup" and key == "wavelength"
#                      and str(widget.value).strip().lower() in {"", "none", "null"})
#             else (float(widget.value) if isinstance(widget, FloatSpinBox)
#                   else int(widget.value) if isinstance(widget, SpinBox)
#                   else bool(widget.value) if isinstance(widget, CheckBox)
#                   else str(widget.value))
#         )
#         save_yaml(ypath, ydoc)

#     for section, mapping in widget_map.items():
#         for key, widget in mapping.items():
#             widget.changed.connect(lambda *_, s=section, k=key, w=widget: on_changed(s, k, w))

#     # Run
#     exec_fn = getattr(app, "exec", None) or getattr(app, "exec_", None)
#     sys.exit(exec_fn())
